services:
  verdaccio:
    image: verdaccio/verdaccio:5
    ports:
      - "127.0.0.1:4873:4873/tcp"
    networks:
      - verdaccio-network
    environment:
      VERDACCIO_PROTOCOL: https
    volumes:
      - verdaccio-storage:/verdaccio/storage
      - type: bind
        source: ./conf
        target: /verdaccio/conf
        read_only: true
      - type: bind
        source: ./plugins
        target: /verdaccio/plugins
        read_only: true

volumes:
  verdaccio-storage:

networks:
  verdaccio-network:
